name: CoreProtectionAssistant
version: ${project.version}
main: ru.allfire.coreprotectionassistant.CoreProtectionAssistant
api-version: '1.21'
author: AllF1RE
description: Advanced staff monitoring and player protection system powered by CoreProtect

softdepend:
  - PlaceholderAPI
  - CoreProtect
  - CMI
  - LuckPerms
  - STCP

commands:
  coreprotectionassistant:
    description: "Main plugin command"
    aliases: [cpa, protect, adminprotect]
  report:
    description: "Report a player"
    aliases: [rep, ticket]

permissions:
  cpa.moder:
    description: "Access to player statistics"
    default: op
  cpa.staff:
    description: "Access to staff statistics"
    default: op
  cpa.warn:
    description: "Can issue warnings"
    default: op
  cpa.warn.clear:
    description: "Can clear warnings"
    default: op
  cpa.report:
    description: "Can use /report command"
    default: true
  cpa.report.see:
    description: "Can see reports"
    default: op
  cpa.report.tp:
    description: "Can teleport to report location"
    default: op
  cpa.reload:
    description: "Can reload configuration"
    default: op
  cpa.bypass.chat:
    description: "Bypass chat filter"
    default: op
